name: screenocr
version: '0.2.0'
summary: Fast hotkey-triggered OCR for Linux/Wayland
description: |
  ScreenOCR is a lightweight OCR utility for Linux that extracts text from
  any screen region with a single hotkey press. Perfect for code snippets,
  documentation, and text extraction.
  
  Features:
  - Press Super+Shift+T to trigger OCR region selection
  - Fast RapidOCR engine (~1-2 second response)
  - Wayland-native XDG Portal screenshot support
  - Smart Python syntax post-processing
  - Automatic clipboard integration
  - Customizable hotkeys
  - Daemon mode with global hotkey support

grade: stable
confinement: classic
base: core22
icon: screenocr.png

apps:
  screenocr:
    command: bin/screenocr-wrapper
    plugs:
      - wayland
      - x11
      - home
      - system-backup
      - audio-playback
    environment:
      PYTHONPATH: $SNAP/lib/python3.10/site-packages:$PYTHONPATH

  daemon:
    command: bin/screenocr-daemon
    daemon: simple
    plugs:
      - wayland
      - x11
      - home
      - system-backup
    environment:
      PYTHONPATH: $SNAP/lib/python3.10/site-packages:$PYTHONPATH

parts:
  screenocr:
    plugin: python
    python-version: python3.10
    python-packages:
      - pip
      - setuptools
      - wheel
      - PySide6
      - opencv-python
      - rapidocr-onnxruntime
      - pillow
      - numpy
      - keyboard
    
    source: .
    build-packages:
      - python3-dev
      - libpython3.10-dev
      
    stage-packages:
      - libxkbcommon0
      - fontconfig-config
      - fonts-dejavu-core
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt6gui6
      - libqt6widgets6
      - libqt6core6
      - libxcb-xinerama0
      - libxcb-shape0
      - libxcb-xfixes0
      - libxcb-render0
      - libxext6
      - libx11-6
      - libxrandr2
      - libxtst6
      - fontconfig
      - libc6
      - libudev1
      - util-linux
      - libpulse0
      - libavcodec-extra
      - libswscale5
    
    # Copy application files
    override-build: |
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      
      # Create wrapper scripts
      cat > $SNAPCRAFT_PART_INSTALL/bin/screenocr-wrapper << 'WRAPPER'
      #!/bin/bash
      export PYTHONPATH=$SNAP/lib/python3.10/site-packages
      exec $SNAP/usr/bin/python3 $SNAP/screenocr/main.py "$@"
      WRAPPER
      
      cat > $SNAPCRAFT_PART_INSTALL/bin/screenocr-daemon << 'DAEMON'
      #!/bin/bash
      export PYTHONPATH=$SNAP/lib/python3.10/site-packages
      exec $SNAP/usr/bin/python3 $SNAP/screenocr/main.py daemon "$@"
      DAEMON
      
      chmod +x $SNAPCRAFT_PART_INSTALL/bin/screenocr-wrapper
      chmod +x $SNAPCRAFT_PART_INSTALL/bin/screenocr-daemon
      
      # Copy application modules
      mkdir -p $SNAPCRAFT_PART_INSTALL/screenocr
      cp main.py ocr_engine.py portal.py overlay.py utils.py hotkey_daemon.py \
        $SNAPCRAFT_PART_INSTALL/screenocr/
